# Generated by Django 5.2.7 on 2025-10-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='districtperformance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
