# Generated by Django 5.2.7 on 2025-10-27 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_districtperformance_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='districtperformance',
            name='month',
        ),
        migrations.RemoveField(
            model_name='districtperformance',
            name='year',
        ),
    ]
